/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DurationRecordInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activities"
      | "activityCount"
      | "approve"
      | "approveSubmission"
      | "balanceOf"
      | "baseUriBronze"
      | "baseUriGold"
      | "baseUriNone"
      | "baseUriSilver"
      | "bronzeThreshold"
      | "categoryThresholds"
      | "claimOrUpgrade"
      | "compareUsersPublic"
      | "confidentialProtocolId"
      | "createActivity"
      | "getApproved"
      | "getEncryptedOverall"
      | "getEncryptedTotalByCategory"
      | "goldThreshold"
      | "grantAccessToMyTotals"
      | "isApprovedForAll"
      | "name"
      | "nonces"
      | "orgCount"
      | "orgs"
      | "owner"
      | "ownerOf"
      | "rankingOptIn"
      | "registerOrganization"
      | "rejectSubmission"
      | "renounceOwnership"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setActivityActive"
      | "setApprovalForAll"
      | "setBaseUris"
      | "setCategoryThresholds"
      | "setGlobalThresholds"
      | "setRankingOptIn"
      | "silverThreshold"
      | "submissionCount"
      | "submissions"
      | "submitHours"
      | "supportsInterface"
      | "symbol"
      | "tokenLevel"
      | "tokenURI"
      | "transferFrom"
      | "transferOwnership"
      | "updateOrganization"
      | "userTokenId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActivityCreated"
      | "ActivityUpdated"
      | "Approval"
      | "ApprovalForAll"
      | "CategoryThresholdsUpdated"
      | "CredentialMinted"
      | "CredentialUpgraded"
      | "OptInRanking"
      | "OrganizationRegistered"
      | "OrganizationUpdated"
      | "OwnershipTransferred"
      | "SubmissionApproved"
      | "SubmissionCreated"
      | "SubmissionRejected"
      | "ThresholdsUpdated"
      | "TotalsUpdated"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activities",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activityCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveSubmission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "baseUriBronze",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseUriGold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseUriNone",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseUriSilver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bronzeThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "categoryThresholds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimOrUpgrade",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "compareUsersPublic",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createActivity",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedOverall",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotalByCategory",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "goldThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccessToMyTotals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "orgCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "orgs", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rankingOptIn",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOrganization",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectSubmission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setActivityActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseUris",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCategoryThresholds",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGlobalThresholds",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRankingOptIn",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "silverThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submissionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submissions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitHours",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenLevel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOrganization",
    values: [BigNumberish, string, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "userTokenId",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "activities", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activityCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "baseUriBronze",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseUriGold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseUriNone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseUriSilver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bronzeThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "categoryThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimOrUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "compareUsersPublic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedOverall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotalByCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "goldThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccessToMyTotals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orgCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orgs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rankingOptIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOrganization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setActivityActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseUris",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCategoryThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRankingOptIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "silverThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitHours",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenLevel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOrganization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTokenId",
    data: BytesLike
  ): Result;
}

export namespace ActivityCreatedEvent {
  export type InputTuple = [
    activityId: BigNumberish,
    orgId: BigNumberish,
    category: BytesLike
  ];
  export type OutputTuple = [
    activityId: bigint,
    orgId: bigint,
    category: string
  ];
  export interface OutputObject {
    activityId: bigint;
    orgId: bigint;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActivityUpdatedEvent {
  export type InputTuple = [activityId: BigNumberish, active: boolean];
  export type OutputTuple = [activityId: bigint, active: boolean];
  export interface OutputObject {
    activityId: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CategoryThresholdsUpdatedEvent {
  export type InputTuple = [
    category: BytesLike,
    bronze: BigNumberish,
    silver: BigNumberish,
    gold: BigNumberish
  ];
  export type OutputTuple = [
    category: string,
    bronze: bigint,
    silver: bigint,
    gold: bigint
  ];
  export interface OutputObject {
    category: string;
    bronze: bigint;
    silver: bigint;
    gold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialMintedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenId: BigNumberish,
    level: BigNumberish
  ];
  export type OutputTuple = [user: string, tokenId: bigint, level: bigint];
  export interface OutputObject {
    user: string;
    tokenId: bigint;
    level: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialUpgradedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenId: BigNumberish,
    fromLevel: BigNumberish,
    toLevel: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tokenId: bigint,
    fromLevel: bigint,
    toLevel: bigint
  ];
  export interface OutputObject {
    user: string;
    tokenId: bigint;
    fromLevel: bigint;
    toLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptInRankingEvent {
  export type InputTuple = [user: AddressLike, enabled: boolean];
  export type OutputTuple = [user: string, enabled: boolean];
  export interface OutputObject {
    user: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrganizationRegisteredEvent {
  export type InputTuple = [
    orgId: BigNumberish,
    name: string,
    admin: AddressLike
  ];
  export type OutputTuple = [orgId: bigint, name: string, admin: string];
  export interface OutputObject {
    orgId: bigint;
    name: string;
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrganizationUpdatedEvent {
  export type InputTuple = [
    orgId: BigNumberish,
    name: string,
    admin: AddressLike,
    active: boolean
  ];
  export type OutputTuple = [
    orgId: bigint,
    name: string,
    admin: string,
    active: boolean
  ];
  export interface OutputObject {
    orgId: bigint;
    name: string;
    admin: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionApprovedEvent {
  export type InputTuple = [submissionId: BigNumberish, approver: AddressLike];
  export type OutputTuple = [submissionId: bigint, approver: string];
  export interface OutputObject {
    submissionId: bigint;
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionCreatedEvent {
  export type InputTuple = [
    submissionId: BigNumberish,
    user: AddressLike,
    activityId: BigNumberish,
    category: BytesLike
  ];
  export type OutputTuple = [
    submissionId: bigint,
    user: string,
    activityId: bigint,
    category: string
  ];
  export interface OutputObject {
    submissionId: bigint;
    user: string;
    activityId: bigint;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionRejectedEvent {
  export type InputTuple = [submissionId: BigNumberish, approver: AddressLike];
  export type OutputTuple = [submissionId: bigint, approver: string];
  export interface OutputObject {
    submissionId: bigint;
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdsUpdatedEvent {
  export type InputTuple = [
    bronze: BigNumberish,
    silver: BigNumberish,
    gold: BigNumberish
  ];
  export type OutputTuple = [bronze: bigint, silver: bigint, gold: bigint];
  export interface OutputObject {
    bronze: bigint;
    silver: bigint;
    gold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TotalsUpdatedEvent {
  export type InputTuple = [user: AddressLike, category: BytesLike];
  export type OutputTuple = [user: string, category: string];
  export interface OutputObject {
    user: string;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DurationRecord extends BaseContract {
  connect(runner?: ContractRunner | null): DurationRecord;
  waitForDeployment(): Promise<this>;

  interface: DurationRecordInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activities: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, boolean] & {
        orgId: bigint;
        category: string;
        minHours: string;
        maxHours: string;
        active: boolean;
      }
    ],
    "view"
  >;

  activityCount: TypedContractMethod<[], [bigint], "view">;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveSubmission: TypedContractMethod<
    [submissionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  baseUriBronze: TypedContractMethod<[], [string], "view">;

  baseUriGold: TypedContractMethod<[], [string], "view">;

  baseUriNone: TypedContractMethod<[], [string], "view">;

  baseUriSilver: TypedContractMethod<[], [string], "view">;

  bronzeThreshold: TypedContractMethod<[], [bigint], "view">;

  categoryThresholds: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint] & {
        bronze: bigint;
        silver: bigint;
        gold: bigint;
      }
    ],
    "view"
  >;

  claimOrUpgrade: TypedContractMethod<[], [void], "nonpayable">;

  compareUsersPublic: TypedContractMethod<
    [a: AddressLike, b: AddressLike],
    [string],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createActivity: TypedContractMethod<
    [
      orgId: BigNumberish,
      category: BytesLike,
      minHoursPlain: BigNumberish,
      maxHoursPlain: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getEncryptedOverall: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getEncryptedTotalByCategory: TypedContractMethod<
    [user: AddressLike, category: BytesLike],
    [string],
    "view"
  >;

  goldThreshold: TypedContractMethod<[], [bigint], "view">;

  grantAccessToMyTotals: TypedContractMethod<
    [category: BytesLike],
    [void],
    "nonpayable"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  orgCount: TypedContractMethod<[], [bigint], "view">;

  orgs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean] & {
        admin: string;
        name: string;
        active: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  rankingOptIn: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  registerOrganization: TypedContractMethod<
    [name: string, admin: AddressLike],
    [bigint],
    "nonpayable"
  >;

  rejectSubmission: TypedContractMethod<
    [submissionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setActivityActive: TypedContractMethod<
    [activityId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setBaseUris: TypedContractMethod<
    [noneUri: string, bronzeUri: string, silverUri: string, goldUri: string],
    [void],
    "nonpayable"
  >;

  setCategoryThresholds: TypedContractMethod<
    [
      category: BytesLike,
      bronze: BigNumberish,
      silver: BigNumberish,
      gold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setGlobalThresholds: TypedContractMethod<
    [bronze: BigNumberish, silver: BigNumberish, gold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRankingOptIn: TypedContractMethod<
    [enabled: boolean],
    [void],
    "nonpayable"
  >;

  silverThreshold: TypedContractMethod<[], [bigint], "view">;

  submissionCount: TypedContractMethod<[], [bigint], "view">;

  submissions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, string, string, boolean, boolean] & {
        user: string;
        orgId: bigint;
        activityId: bigint;
        category: string;
        encryptedHours: string;
        approved: boolean;
        rejected: boolean;
      }
    ],
    "view"
  >;

  submitHours: TypedContractMethod<
    [
      orgId: BigNumberish,
      activityId: BigNumberish,
      category: BytesLike,
      cipherHours: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenLevel: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateOrganization: TypedContractMethod<
    [orgId: BigNumberish, name: string, admin: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;

  userTokenId: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activities"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, boolean] & {
        orgId: bigint;
        category: string;
        minHours: string;
        maxHours: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "activityCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveSubmission"
  ): TypedContractMethod<[submissionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseUriBronze"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "baseUriGold"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "baseUriNone"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "baseUriSilver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bronzeThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "categoryThresholds"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint] & {
        bronze: bigint;
        silver: bigint;
        gold: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimOrUpgrade"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "compareUsersPublic"
  ): TypedContractMethod<
    [a: AddressLike, b: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createActivity"
  ): TypedContractMethod<
    [
      orgId: BigNumberish,
      category: BytesLike,
      minHoursPlain: BigNumberish,
      maxHoursPlain: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedOverall"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTotalByCategory"
  ): TypedContractMethod<
    [user: AddressLike, category: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "goldThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantAccessToMyTotals"
  ): TypedContractMethod<[category: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "orgCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orgs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean] & {
        admin: string;
        name: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "rankingOptIn"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerOrganization"
  ): TypedContractMethod<
    [name: string, admin: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectSubmission"
  ): TypedContractMethod<[submissionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setActivityActive"
  ): TypedContractMethod<
    [activityId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseUris"
  ): TypedContractMethod<
    [noneUri: string, bronzeUri: string, silverUri: string, goldUri: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCategoryThresholds"
  ): TypedContractMethod<
    [
      category: BytesLike,
      bronze: BigNumberish,
      silver: BigNumberish,
      gold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGlobalThresholds"
  ): TypedContractMethod<
    [bronze: BigNumberish, silver: BigNumberish, gold: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRankingOptIn"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "silverThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submissionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submissions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, string, string, boolean, boolean] & {
        user: string;
        orgId: bigint;
        activityId: bigint;
        category: string;
        encryptedHours: string;
        approved: boolean;
        rejected: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitHours"
  ): TypedContractMethod<
    [
      orgId: BigNumberish,
      activityId: BigNumberish,
      category: BytesLike,
      cipherHours: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenLevel"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateOrganization"
  ): TypedContractMethod<
    [orgId: BigNumberish, name: string, admin: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userTokenId"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "ActivityCreated"
  ): TypedContractEvent<
    ActivityCreatedEvent.InputTuple,
    ActivityCreatedEvent.OutputTuple,
    ActivityCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ActivityUpdated"
  ): TypedContractEvent<
    ActivityUpdatedEvent.InputTuple,
    ActivityUpdatedEvent.OutputTuple,
    ActivityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "CategoryThresholdsUpdated"
  ): TypedContractEvent<
    CategoryThresholdsUpdatedEvent.InputTuple,
    CategoryThresholdsUpdatedEvent.OutputTuple,
    CategoryThresholdsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialMinted"
  ): TypedContractEvent<
    CredentialMintedEvent.InputTuple,
    CredentialMintedEvent.OutputTuple,
    CredentialMintedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialUpgraded"
  ): TypedContractEvent<
    CredentialUpgradedEvent.InputTuple,
    CredentialUpgradedEvent.OutputTuple,
    CredentialUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "OptInRanking"
  ): TypedContractEvent<
    OptInRankingEvent.InputTuple,
    OptInRankingEvent.OutputTuple,
    OptInRankingEvent.OutputObject
  >;
  getEvent(
    key: "OrganizationRegistered"
  ): TypedContractEvent<
    OrganizationRegisteredEvent.InputTuple,
    OrganizationRegisteredEvent.OutputTuple,
    OrganizationRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OrganizationUpdated"
  ): TypedContractEvent<
    OrganizationUpdatedEvent.InputTuple,
    OrganizationUpdatedEvent.OutputTuple,
    OrganizationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionApproved"
  ): TypedContractEvent<
    SubmissionApprovedEvent.InputTuple,
    SubmissionApprovedEvent.OutputTuple,
    SubmissionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionCreated"
  ): TypedContractEvent<
    SubmissionCreatedEvent.InputTuple,
    SubmissionCreatedEvent.OutputTuple,
    SubmissionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionRejected"
  ): TypedContractEvent<
    SubmissionRejectedEvent.InputTuple,
    SubmissionRejectedEvent.OutputTuple,
    SubmissionRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdsUpdated"
  ): TypedContractEvent<
    ThresholdsUpdatedEvent.InputTuple,
    ThresholdsUpdatedEvent.OutputTuple,
    ThresholdsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TotalsUpdated"
  ): TypedContractEvent<
    TotalsUpdatedEvent.InputTuple,
    TotalsUpdatedEvent.OutputTuple,
    TotalsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "ActivityCreated(uint256,uint256,bytes32)": TypedContractEvent<
      ActivityCreatedEvent.InputTuple,
      ActivityCreatedEvent.OutputTuple,
      ActivityCreatedEvent.OutputObject
    >;
    ActivityCreated: TypedContractEvent<
      ActivityCreatedEvent.InputTuple,
      ActivityCreatedEvent.OutputTuple,
      ActivityCreatedEvent.OutputObject
    >;

    "ActivityUpdated(uint256,bool)": TypedContractEvent<
      ActivityUpdatedEvent.InputTuple,
      ActivityUpdatedEvent.OutputTuple,
      ActivityUpdatedEvent.OutputObject
    >;
    ActivityUpdated: TypedContractEvent<
      ActivityUpdatedEvent.InputTuple,
      ActivityUpdatedEvent.OutputTuple,
      ActivityUpdatedEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "CategoryThresholdsUpdated(bytes32,uint32,uint32,uint32)": TypedContractEvent<
      CategoryThresholdsUpdatedEvent.InputTuple,
      CategoryThresholdsUpdatedEvent.OutputTuple,
      CategoryThresholdsUpdatedEvent.OutputObject
    >;
    CategoryThresholdsUpdated: TypedContractEvent<
      CategoryThresholdsUpdatedEvent.InputTuple,
      CategoryThresholdsUpdatedEvent.OutputTuple,
      CategoryThresholdsUpdatedEvent.OutputObject
    >;

    "CredentialMinted(address,uint256,uint8)": TypedContractEvent<
      CredentialMintedEvent.InputTuple,
      CredentialMintedEvent.OutputTuple,
      CredentialMintedEvent.OutputObject
    >;
    CredentialMinted: TypedContractEvent<
      CredentialMintedEvent.InputTuple,
      CredentialMintedEvent.OutputTuple,
      CredentialMintedEvent.OutputObject
    >;

    "CredentialUpgraded(address,uint256,uint8,uint8)": TypedContractEvent<
      CredentialUpgradedEvent.InputTuple,
      CredentialUpgradedEvent.OutputTuple,
      CredentialUpgradedEvent.OutputObject
    >;
    CredentialUpgraded: TypedContractEvent<
      CredentialUpgradedEvent.InputTuple,
      CredentialUpgradedEvent.OutputTuple,
      CredentialUpgradedEvent.OutputObject
    >;

    "OptInRanking(address,bool)": TypedContractEvent<
      OptInRankingEvent.InputTuple,
      OptInRankingEvent.OutputTuple,
      OptInRankingEvent.OutputObject
    >;
    OptInRanking: TypedContractEvent<
      OptInRankingEvent.InputTuple,
      OptInRankingEvent.OutputTuple,
      OptInRankingEvent.OutputObject
    >;

    "OrganizationRegistered(uint256,string,address)": TypedContractEvent<
      OrganizationRegisteredEvent.InputTuple,
      OrganizationRegisteredEvent.OutputTuple,
      OrganizationRegisteredEvent.OutputObject
    >;
    OrganizationRegistered: TypedContractEvent<
      OrganizationRegisteredEvent.InputTuple,
      OrganizationRegisteredEvent.OutputTuple,
      OrganizationRegisteredEvent.OutputObject
    >;

    "OrganizationUpdated(uint256,string,address,bool)": TypedContractEvent<
      OrganizationUpdatedEvent.InputTuple,
      OrganizationUpdatedEvent.OutputTuple,
      OrganizationUpdatedEvent.OutputObject
    >;
    OrganizationUpdated: TypedContractEvent<
      OrganizationUpdatedEvent.InputTuple,
      OrganizationUpdatedEvent.OutputTuple,
      OrganizationUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SubmissionApproved(uint256,address)": TypedContractEvent<
      SubmissionApprovedEvent.InputTuple,
      SubmissionApprovedEvent.OutputTuple,
      SubmissionApprovedEvent.OutputObject
    >;
    SubmissionApproved: TypedContractEvent<
      SubmissionApprovedEvent.InputTuple,
      SubmissionApprovedEvent.OutputTuple,
      SubmissionApprovedEvent.OutputObject
    >;

    "SubmissionCreated(uint256,address,uint256,bytes32)": TypedContractEvent<
      SubmissionCreatedEvent.InputTuple,
      SubmissionCreatedEvent.OutputTuple,
      SubmissionCreatedEvent.OutputObject
    >;
    SubmissionCreated: TypedContractEvent<
      SubmissionCreatedEvent.InputTuple,
      SubmissionCreatedEvent.OutputTuple,
      SubmissionCreatedEvent.OutputObject
    >;

    "SubmissionRejected(uint256,address)": TypedContractEvent<
      SubmissionRejectedEvent.InputTuple,
      SubmissionRejectedEvent.OutputTuple,
      SubmissionRejectedEvent.OutputObject
    >;
    SubmissionRejected: TypedContractEvent<
      SubmissionRejectedEvent.InputTuple,
      SubmissionRejectedEvent.OutputTuple,
      SubmissionRejectedEvent.OutputObject
    >;

    "ThresholdsUpdated(uint32,uint32,uint32)": TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;
    ThresholdsUpdated: TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;

    "TotalsUpdated(address,bytes32)": TypedContractEvent<
      TotalsUpdatedEvent.InputTuple,
      TotalsUpdatedEvent.OutputTuple,
      TotalsUpdatedEvent.OutputObject
    >;
    TotalsUpdated: TypedContractEvent<
      TotalsUpdatedEvent.InputTuple,
      TotalsUpdatedEvent.OutputTuple,
      TotalsUpdatedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
